# Generated by Django 4.1.5 on 2023-01-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('travel_medium', models.CharField(choices=[('1', 'BUS'), ('2', 'CAR'), ('3', 'TRAIN')], max_length=20)),
                ('assets_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
