# Generated by Django 4.1.5 on 2023-01-12 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_alter_rider_travel_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='date_time',
        ),
        migrations.AddField(
            model_name='rider',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
