# Generated by Django 4.1.5 on 2023-01-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_remove_rider_date_time_rider_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='id',
        ),
        migrations.AlterField(
            model_name='rider',
            name='from_location',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
