# Generated by Django 4.1.5 on 2023-01-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('asset_type', models.CharField(choices=[('1', 'LAPTOP'), ('2', 'TRAVEL_BAG'), ('3', 'PACKAGE')], max_length=20)),
                ('sensitivities', models.CharField(choices=[('1', 'HIGHLY_SENSITIVE'), ('2', 'SENSITIVE'), ('3', 'NORMAL')], max_length=20)),
                ('recipient', models.CharField(max_length=100)),
            ],
        ),
    ]
