# Generated by Django 4.1.5 on 2023-01-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='assets',
            field=models.IntegerField(default=0, verbose_name='No of assets'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='asset_type',
            field=models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('TRAVEL_BAG', 'TRAVEL_BAG'), ('PACKAGE', 'PACKAGE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requester',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='sensitivities',
            field=models.CharField(choices=[('HIGHLY_SENSITIVE', 'HIGHLY_SENSITIVE'), ('SENSITIVE', 'SENSITIVE'), ('NORMAL', 'NORMAL')], max_length=20),
        ),
    ]
