# Generated by Django 4.1.5 on 2023-01-12 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0002_requester_assets_alter_requester_asset_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requester',
            name='date_time',
        ),
        migrations.AddField(
            model_name='requester',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
